name: Build
on: push
jobs:
    build:
        name: Linux-amd64
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.0

            - name: Build
              run: ./build.sh

            - name: Upload Static Library
              uses: actions/upload-artifact@v3
              with:
                  name: libtercom.a
                  path: ./build/libtercom.a

            - name: Upload Shared Library
              uses: actions/upload-artifact@v3
              with:
                  name: libtercom.so
                  path: ./build/libtercom.so
